android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official

# Fix fondamentale per Termux/Android su ARM
android.aapt2DaemonEnabled=false

# Forza Gradle a usare l'AAPT2 ARM corretto dei build-tools
android.aapt2FromMavenOverride=/data/data/com.termux/files/usr/lib/android-sdk/build-tools/34.0.0/aapt2
